# Generated by Django 3.0.3 on 2020-03-04 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='replies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='retweets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poster',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
            preserve_default=False,
        ),
    ]
