# Generated by Django 3.0.3 on 2020-03-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200304_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='poster_img_path',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
