# Generated by Django 3.0.3 on 2020-03-08 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_poster_poster_img_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.Poster'),
        ),
        migrations.AddField(
            model_name='poster',
            name='poster_password',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
