# Generated by Django 3.0.3 on 2020-03-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200308_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='poster_pfp',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
