# Generated by Django 3.0.3 on 2020-03-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_poster_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='poster_img_path',
        ),
    ]
