# Generated by Django 3.0.3 on 2020-03-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_liked',
        ),
        migrations.AddField(
            model_name='poster',
            name='liked_posts',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
