# Generated by Django 3.0.3 on 2020-03-27 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200326_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='replying_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='posts.Post'),
        ),
    ]
